-- Minimal schema for Mapping Client (Supabase / Postgres)
-- 1) Run this in Supabase SQL Editor
-- 2) Then enable RLS + policies (see bottom)

create table if not exists public.node_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  label text not null,
  icon text,
  created_at timestamptz not null default now()
);

create table if not exists public.nodes (
  id bigint generated by default as identity primary key,
  node_type_id bigint not null references public.node_types(id),
  code text not null unique,
  name text,
  latitude double precision,
  longitude double precision,
  address text,
  photo_path text,
  notes text,
  topology_x integer default 100,
  topology_y integer default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  source_node_id bigint not null references public.nodes(id) on delete cascade,
  target_node_id bigint not null references public.nodes(id) on delete cascade,
  cable_type text,
  core_count integer,
  core_number text,
  pon_name text,
  odc_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_node_id, target_node_id)
);

create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  node_id bigint references public.nodes(id) on delete set null,
  category text not null default 'kerusakan',
  title text not null,
  description text,
  reporter_name text,
  reporter_contact text,
  photo_path text,
  noc_admin_name text,
  technician_name text,
  technician_contact text,
  technician_email text,
  work_order_notes text,
  technician_report text,
  status text not null default 'reported',
  assigned_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_reports (
  id bigint generated by default as identity primary key,
  incident_id bigint references public.incidents(id) on delete set null,
  node_id bigint references public.nodes(id) on delete set null,
  technician_name text,
  report_title text not null,
  description text not null,
  photo_path text,
  status text not null default 'completed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- User profiles (role gating in UI). This is separate from auth.users.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  role text not null default 'teknisi',
  is_active integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Optional seed node types
insert into public.node_types (id, name, label, icon)
values
  (1, 'odc', 'ODC', 'odc.png'),
  (2, 'pon', 'PON', 'pon.png'),
  (3, 'box', 'Box / ODP', 'box.png'),
  (4, 'pole', 'Tiang', 'pole.png'),
  (5, 'customer', 'Customer', 'customer.png'),
  (6, 'server', 'Server', 'server.png'),
  (7, 'olc', 'OLC', 'olc.png')
on conflict (id) do nothing;

-- ========= RLS (temporary, simple) =========
-- For "sementara", allow authenticated users to read/write everything.
-- Tighten later (per-role/per-tenant) once stable.

alter table public.node_types enable row level security;
alter table public.nodes enable row level security;
alter table public.links enable row level security;
alter table public.incidents enable row level security;
alter table public.work_reports enable row level security;
alter table public.profiles enable row level security;

do $$ begin
  create policy "auth read node_types" on public.node_types for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "auth write node_types" on public.node_types for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "auth read nodes" on public.nodes for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "auth write nodes" on public.nodes for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "auth read links" on public.links for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "auth write links" on public.links for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "auth read incidents" on public.incidents for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "auth write incidents" on public.incidents for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "auth read work_reports" on public.work_reports for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "auth write work_reports" on public.work_reports for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "auth read profiles" on public.profiles for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "auth write profiles" on public.profiles for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

